/**
 * Unit Tests for TRDIFF10 Binary Patch Application
 *
 * Tests the bspatch implementation against real TRDIFF10 patches
 * generated by zig-bsdiff v0.1.19 (stored as test fixtures).
 */

import { describe, expect, test } from "bun:test";
import { unlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { applyPatch, offtin, parsePatchHeader } from "../../src/lib/bspatch.js";

const FIXTURES_DIR = join(import.meta.dir, "../fixtures/patches");

describe("offtin", () => {
  test("reads zero", () => {
    const buf = new Uint8Array(8);
    expect(offtin(buf, 0)).toBe(0);
  });

  test("reads positive value 1", () => {
    const buf = new Uint8Array(8);
    buf[0] = 1; // LE: least significant byte
    expect(offtin(buf, 0)).toBe(1);
  });

  test("reads positive value 256", () => {
    const buf = new Uint8Array(8);
    buf[1] = 1; // 256 in LE
    expect(offtin(buf, 0)).toBe(256);
  });

  test("reads negative value -1", () => {
    // zig-bsdiff sign-magnitude: magnitude=1, sign bit set in byte 7
    const buf = new Uint8Array(8);
    buf[0] = 1;
    buf[7] = 0x80; // Sign bit
    expect(offtin(buf, 0)).toBe(-1);
  });

  test("reads negative value -256", () => {
    const buf = new Uint8Array(8);
    buf[1] = 1; // magnitude = 256
    buf[7] = 0x80;
    expect(offtin(buf, 0)).toBe(-256);
  });

  test("reads from offset", () => {
    const buf = new Uint8Array(16);
    buf[8] = 42;
    expect(offtin(buf, 8)).toBe(42);
  });

  test("reads large positive value", () => {
    const buf = new Uint8Array(8);
    // 0x01_00_00_00 = 16,777,216 in LE: byte 3 = 0x01
    buf[3] = 1;
    expect(offtin(buf, 0)).toBe(16_777_216);
  });

  test("reads value spanning both 32-bit halves", () => {
    const buf = new Uint8Array(8);
    // Low 32 bits: 0
    // High 32 bits: 1 → value = 1 * 2^32 = 4,294,967,296
    buf[4] = 1;
    expect(offtin(buf, 0)).toBe(4_294_967_296);
  });
});

describe("parsePatchHeader", () => {
  test("rejects too-small buffer", () => {
    expect(() => parsePatchHeader(new Uint8Array(31))).toThrow(
      "Patch too small"
    );
  });

  test("rejects invalid magic", () => {
    const buf = new Uint8Array(32);
    buf.set(new TextEncoder().encode("BSDIFF40"));
    expect(() => parsePatchHeader(buf)).toThrow("Invalid patch format");
  });

  test("rejects negative header values", () => {
    const buf = new Uint8Array(32);
    buf.set(new TextEncoder().encode("TRDIFF10"));
    // Set controlLen to -1 (sign bit in byte 15)
    buf[8] = 1;
    buf[15] = 0x80;
    expect(() => parsePatchHeader(buf)).toThrow("negative length");
  });

  test("parses valid small fixture header", async () => {
    const patchData = new Uint8Array(
      await Bun.file(join(FIXTURES_DIR, "small.trdiff10")).arrayBuffer()
    );
    const header = parsePatchHeader(patchData);
    expect(header.controlLen).toBeGreaterThan(0);
    expect(header.diffLen).toBeGreaterThan(0);
    expect(header.newSize).toBe(54); // "Hello, World! This is the new file content. Version 2."
  });

  test("parses valid large fixture header", async () => {
    const patchData = new Uint8Array(
      await Bun.file(join(FIXTURES_DIR, "large.trdiff10")).arrayBuffer()
    );
    const header = parsePatchHeader(patchData);
    expect(header.controlLen).toBeGreaterThan(0);
    expect(header.diffLen).toBeGreaterThanOrEqual(0);
    expect(header.newSize).toBe(65_536);
  });
});

describe("applyPatch", () => {
  function tempFile(name: string): string {
    return join(tmpdir(), `bspatch-test-${Date.now()}-${name}`);
  }

  test("patches small text files correctly", async () => {
    const oldPath = join(FIXTURES_DIR, "small-old.bin");
    const patchData = new Uint8Array(
      await Bun.file(join(FIXTURES_DIR, "small.trdiff10")).arrayBuffer()
    );
    const destPath = tempFile("small-out.bin");

    try {
      const sha256 = await applyPatch(oldPath, patchData, destPath);

      // Verify output matches expected new file
      const expected = await Bun.file(
        join(FIXTURES_DIR, "small-new.bin")
      ).arrayBuffer();
      const actual = await Bun.file(destPath).arrayBuffer();
      expect(new Uint8Array(actual)).toEqual(new Uint8Array(expected));

      // Verify SHA-256 matches
      const expectedHash = new Bun.CryptoHasher("sha256")
        .update(new Uint8Array(expected))
        .digest("hex");
      expect(sha256).toBe(expectedHash);
    } finally {
      try {
        unlinkSync(destPath);
      } catch {
        // Ignore cleanup errors
      }
    }
  });

  test("patches large binary files correctly", async () => {
    const oldPath = join(FIXTURES_DIR, "large-old.bin");
    const patchData = new Uint8Array(
      await Bun.file(join(FIXTURES_DIR, "large.trdiff10")).arrayBuffer()
    );
    const destPath = tempFile("large-out.bin");

    try {
      const sha256 = await applyPatch(oldPath, patchData, destPath);

      const expected = await Bun.file(
        join(FIXTURES_DIR, "large-new.bin")
      ).arrayBuffer();
      const actual = await Bun.file(destPath).arrayBuffer();
      expect(new Uint8Array(actual)).toEqual(new Uint8Array(expected));

      const expectedHash = new Bun.CryptoHasher("sha256")
        .update(new Uint8Array(expected))
        .digest("hex");
      expect(sha256).toBe(expectedHash);
    } finally {
      try {
        unlinkSync(destPath);
      } catch {
        // Ignore cleanup errors
      }
    }
  });

  test("returns correct SHA-256 hex digest", async () => {
    const oldPath = join(FIXTURES_DIR, "small-old.bin");
    const patchData = new Uint8Array(
      await Bun.file(join(FIXTURES_DIR, "small.trdiff10")).arrayBuffer()
    );
    const destPath = tempFile("sha256-out.bin");

    try {
      const sha256 = await applyPatch(oldPath, patchData, destPath);
      // Known SHA-256 of "Hello, World! This is the new file content. Version 2."
      expect(sha256).toMatch(/^[0-9a-f]{64}$/);
      expect(sha256.length).toBe(64);
    } finally {
      try {
        unlinkSync(destPath);
      } catch {
        // Ignore cleanup errors
      }
    }
  });

  test("rejects truncated patch (header claims more data than exists)", () => {
    // Header says controlLen=100 but patch is only 32 bytes
    const truncated = new Uint8Array(32);
    truncated.set(new TextEncoder().encode("TRDIFF10"));
    truncated[8] = 100; // controlLen = 100

    expect(() => parsePatchHeader(truncated)).toThrow("exceed file size");
  });

  test("rejects non-TRDIFF10 magic", async () => {
    const oldPath = join(FIXTURES_DIR, "small-old.bin");
    const buf = new Uint8Array(64);
    buf.set(new TextEncoder().encode("BSDIFF40"));
    const destPath = tempFile("badmagic-out.bin");

    try {
      await expect(applyPatch(oldPath, buf, destPath)).rejects.toThrow(
        "Invalid patch format"
      );
    } finally {
      try {
        unlinkSync(destPath);
      } catch {
        // Ignore cleanup errors
      }
    }
  });
});
